### ISSUE TITLE
用Gitment替换duoshuo来为基于hexo的静态网站提供评论功能。 | 夕阳下的奔跑

### ISSUE THREAD

**Issue by xintq** [xintq/xintq.net.comment.repo#10]
http://xintq.net/2017/05/02/use-gitment-for-comment/

**Comment by haofangyuan** [comment]
test

**Comment by Wangzhike** [comment]
test!

**Comment by xuanxiaodeyu** [comment]
评论的字体可以改吗？我的博客背景是黑色，评论看不清

**Comment by xintq** [comment]
@xuanxiaodeyu  修改<%- config.root %>js/gitment-theme-default.css" 中的背景色样式就可以了

**Comment by xuanxiaodeyu** [comment]
default.css里面有好多背景色属性啊，具体是哪个对应评论的背景色呢？这是我的博客（http://www.sunyang.xyz/2017/09/02/My-New-Post/）评论现在的颜色好像是透明的。大神能不能帮我看看具体是该哪个值呢?

**Comment by xintq** [comment]
@xuanxiaodeyu  如果只需要让你的评论区看清楚的话，你可以只修改`gitment-theme-default.css`里面的`.gitment-container`，在其中新定义一个CSS属性修改一下原本透明的背景色：`background-color`，像这样：
``` css
.gitment-container {
  font-family: sans-serif;
  font-size: 14px;
  line-height: 1.5;
  color: #333;
  word-wrap: break-word;
  background-color: white
}
```
或者，你也可以只需要将上面的CSS样式中的前景色修改一下，默认透明的评论背景区，白色的文字，加上你黑色的博客背景应该能看清楚吧：
``` css
.gitment-container {
  font-family: sans-serif;
  font-size: 14px;
  line-height: 1.5;
  color: white;
  word-wrap: break-word;
}
```

如果想具体的控制评论区的各个部分的话，可以自己在`gitment-theme-default.css`文件中追加一些CSS样式，例如：
```css
.gitment-comments-list { /*这是整个评论列表的样式*/
  color: black;
  background-color: white;
}
.gitment-comment { /*这是每条列表的样式，也可以自己定义背景色和文件颜色*/
}
```
